# Importing the dependencies

In [1]:
import numpy as np
import pandas as pd
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Data Collection and Processing

In [2]:
movies_data = pd.read_csv('movies.csv',encoding = 'latin1')

In [3]:
movies_data.head()

movie title                  Run Time Rating  \
0                  Top Gun: Maverick  $170,000,000 (estimated)    8.6   
1            Jurassic World Dominion        2 hours 27 minutes      6   
2                          Lightyear               $71,101,257    5.2   
3                         Spiderhead              not-released    5.4   
4  Everything Everywhere All at Once        2 hours 19 minutes    8.3   

  User Rating                               Generes  \
0        187K                   ['Action', 'Drama']   
1         56K     ['Action', 'Adventure', 'Sci-Fi']   
2         32K  ['Animation', 'Action', 'Adventure']   
3         23K          ['Action', 'Crime', 'Drama']   
4        124K     ['Action', 'Adventure', 'Comedy']   

                                            Overview  \
0  After more than thirty years of service as one...   
1  Four years after the destruction of Isla Nubla...   
2  While spending years attempting to return home...   
3  In the near future, convicts are offered the c...   
4  An aging Chinese immigrant is swept up in an i...   

                                        Plot Kyeword         Director  \
0  ['fighter jet', 'sequel', 'u.s. navy', 'fighte...  Joseph Kosinski   
1  ['dinosaur', 'jurassic park', 'tyrannosaurus r...  Colin Trevorrow   
2  ['galaxy', 'spaceship', 'robot', 'rocket', 'sp...    Angus MacLane   
3  ['discover', 'medical', 'test', 'reality', 'fi...  Joseph Kosinski   
4  ['multiverse', 'saving the world', 'mother dau...         Dan Kwan   

                                         Top 5 Casts            Writer  year  \
0  ['Jack Epps Jr.', 'Peter Craig', 'Tom Cruise',...          Jim Cash  2022   
1  ['Colin Trevorrow', 'Derek Connolly', 'Chris P...  Emily Carmichael  2022   
2  ['Jason Headley', 'Matthew Aldrich', 'Chris Ev...     Angus MacLane  2022   
3  ['Rhett Reese', 'Paul Wernick', 'Chris Hemswor...   George Saunders  2022   
4  ['Dan Kwan', 'Daniel Scheinert', 'Michelle Yeo...  Daniel Scheinert  2022   

                 path  
0   /title/tt1745960/  
1   /title/tt8041270/  
2  /title/tt10298810/  
3   /title/tt9783600/  
4   /title/tt6710474/

In [4]:
movies_data.shape

(11296, 12)

In [5]:
movies_data = movies_data.drop(['Run Time','Writer'],axis = 1)
movies_data.head()

movie title Rating User Rating  \
0                  Top Gun: Maverick    8.6        187K   
1            Jurassic World Dominion      6         56K   
2                          Lightyear    5.2         32K   
3                         Spiderhead    5.4         23K   
4  Everything Everywhere All at Once    8.3        124K   

                                Generes  \
0                   ['Action', 'Drama']   
1     ['Action', 'Adventure', 'Sci-Fi']   
2  ['Animation', 'Action', 'Adventure']   
3          ['Action', 'Crime', 'Drama']   
4     ['Action', 'Adventure', 'Comedy']   

                                            Overview  \
0  After more than thirty years of service as one...   
1  Four years after the destruction of Isla Nubla...   
2  While spending years attempting to return home...   
3  In the near future, convicts are offered the c...   
4  An aging Chinese immigrant is swept up in an i...   

                                        Plot Kyeword         Director  \
0  ['fighter jet', 'sequel', 'u.s. navy', 'fighte...  Joseph Kosinski   
1  ['dinosaur', 'jurassic park', 'tyrannosaurus r...  Colin Trevorrow   
2  ['galaxy', 'spaceship', 'robot', 'rocket', 'sp...    Angus MacLane   
3  ['discover', 'medical', 'test', 'reality', 'fi...  Joseph Kosinski   
4  ['multiverse', 'saving the world', 'mother dau...         Dan Kwan   

                                         Top 5 Casts  year                path  
0  ['Jack Epps Jr.', 'Peter Craig', 'Tom Cruise',...  2022   /title/tt1745960/  
1  ['Colin Trevorrow', 'Derek Connolly', 'Chris P...  2022   /title/tt8041270/  
2  ['Jason Headley', 'Matthew Aldrich', 'Chris Ev...  2022  /title/tt10298810/  
3  ['Rhett Reese', 'Paul Wernick', 'Chris Hemswor...  2022   /title/tt9783600/  
4  ['Dan Kwan', 'Daniel Scheinert', 'Michelle Yeo...  2022   /title/tt6710474/

In [ ]:
movies_data['path'] = movies_data['path']

In [6]:
# Making a ID Column

id_list= np.arange(11296)
movies_data.insert(0, 'id', id_list)
movies_data.head()

id                        movie title Rating User Rating  \
0   0                  Top Gun: Maverick    8.6        187K   
1   1            Jurassic World Dominion      6         56K   
2   2                          Lightyear    5.2         32K   
3   3                         Spiderhead    5.4         23K   
4   4  Everything Everywhere All at Once    8.3        124K   

                                Generes  \
0                   ['Action', 'Drama']   
1     ['Action', 'Adventure', 'Sci-Fi']   
2  ['Animation', 'Action', 'Adventure']   
3          ['Action', 'Crime', 'Drama']   
4     ['Action', 'Adventure', 'Comedy']   

                                            Overview  \
0  After more than thirty years of service as one...   
1  Four years after the destruction of Isla Nubla...   
2  While spending years attempting to return home...   
3  In the near future, convicts are offered the c...   
4  An aging Chinese immigrant is swept up in an i...   

                                        Plot Kyeword         Director  \
0  ['fighter jet', 'sequel', 'u.s. navy', 'fighte...  Joseph Kosinski   
1  ['dinosaur', 'jurassic park', 'tyrannosaurus r...  Colin Trevorrow   
2  ['galaxy', 'spaceship', 'robot', 'rocket', 'sp...    Angus MacLane   
3  ['discover', 'medical', 'test', 'reality', 'fi...  Joseph Kosinski   
4  ['multiverse', 'saving the world', 'mother dau...         Dan Kwan   

                                         Top 5 Casts  year                path  
0  ['Jack Epps Jr.', 'Peter Craig', 'Tom Cruise',...  2022   /title/tt1745960/  
1  ['Colin Trevorrow', 'Derek Connolly', 'Chris P...  2022   /title/tt8041270/  
2  ['Jason Headley', 'Matthew Aldrich', 'Chris Ev...  2022  /title/tt10298810/  
3  ['Rhett Reese', 'Paul Wernick', 'Chris Hemswor...  2022   /title/tt9783600/  
4  ['Dan Kwan', 'Daniel Scheinert', 'Michelle Yeo...  2022   /title/tt6710474/

In [7]:
movies_data.isna().sum()

id              0
movie title     0
Rating          0
User Rating     0
Generes         0
Overview        0
Plot Kyeword    0
Director        0
Top 5 Casts     0
year            0
path            0
dtype: int64

In [8]:
import re

def generalise(text):
    text = text.lower()
    text = re.sub('[^a-z ]',' ',text)
    return text

In [9]:
movies_data['Generes'] = movies_data['Generes'].apply(generalise)
movies_data['Plot Kyeword'] = movies_data['Plot Kyeword'].apply(generalise)
movies_data['Top 5 Casts'] = movies_data['Top 5 Casts'].apply(generalise)

In [10]:
movies_data.head()

id                        movie title Rating User Rating  \
0   0                  Top Gun: Maverick    8.6        187K   
1   1            Jurassic World Dominion      6         56K   
2   2                          Lightyear    5.2         32K   
3   3                         Spiderhead    5.4         23K   
4   4  Everything Everywhere All at Once    8.3        124K   

                                Generes  \
0                     action    drama     
1       action    adventure    sci fi     
2    animation    action    adventure     
3            action    crime    drama     
4       action    adventure    comedy     

                                            Overview  \
0  After more than thirty years of service as one...   
1  Four years after the destruction of Isla Nubla...   
2  While spending years attempting to return home...   
3  In the near future, convicts are offered the c...   
4  An aging Chinese immigrant is swept up in an i...   

                                        Plot Kyeword         Director  \
0    fighter jet    sequel    u s  navy    fighte...  Joseph Kosinski   
1    dinosaur    jurassic park    tyrannosaurus r...  Colin Trevorrow   
2    galaxy    spaceship    robot    rocket    sp...    Angus MacLane   
3    discover    medical    test    reality    fi...  Joseph Kosinski   
4    multiverse    saving the world    mother dau...         Dan Kwan   

                                         Top 5 Casts  year                path  
0    jack epps jr     peter craig    tom cruise  ...  2022   /title/tt1745960/  
1    colin trevorrow    derek connolly    chris p...  2022   /title/tt8041270/  
2    jason headley    matthew aldrich    chris ev...  2022  /title/tt10298810/  
3    rhett reese    paul wernick    chris hemswor...  2022   /title/tt9783600/  
4    dan kwan    daniel scheinert    michelle yeo...  2022   /title/tt6710474/

In [11]:
combined_features = movies_data['Generes']+' '+movies_data['Plot Kyeword']+' '+movies_data['Overview']+' '+movies_data['Top 5 Casts']+' '+movies_data['Director']

def test(input):
    input = " ".join(input.split())
    return input
    
combined_features = combined_features.apply(test)
print(combined_features)

0        action drama fighter jet sequel u s navy fight...
1        action adventure sci fi dinosaur jurassic park...
2        animation action adventure galaxy spaceship ro...
3        action crime drama discover medical test reali...
4        action adventure comedy multiverse saving the ...
                               ...                        
11291    adventure comedy crime hostage male rear nudit...
11292    crime drama thriller girl christmas christmas ...
11293    comedy crime drama character names in title fo...
11294    comedy crime family christmas slapstick comedy...
11295    crime horror A gang initiation goes wrong when...
Length: 11296, dtype: object


In [12]:
vectorizer = TfidfVectorizer()
feature_vectors = vectorizer.fit_transform(combined_features)

# Cosine Similarity

In [13]:
similarity = cosine_similarity(feature_vectors)

In [14]:
print(similarity)

[[1.         0.02494806 0.01624162 ... 0.00982355 0.00890728 0.01072509]
 [0.02494806 1.         0.02521631 ... 0.01800875 0.03193997 0.04016155]
 [0.01624162 0.02521631 1.         ... 0.00328068 0.02932479 0.00342227]
 ...
 [0.00982355 0.01800875 0.00328068 ... 1.         0.01483708 0.01073979]
 [0.00890728 0.03193997 0.02932479 ... 0.01483708 1.         0.00396738]
 [0.01072509 0.04016155 0.00342227 ... 0.01073979 0.00396738 1.        ]]


# Movie Recommendation System

In [15]:
movie_name = input(' Enter your favourite movie name : ')

list_of_all_titles = movies_data['movie title'].tolist()

find_close_match = difflib.get_close_matches(movie_name, list_of_all_titles)

close_match = find_close_match[0]

id_of_the_movie = movies_data[movies_data['movie title'] == close_match]['id'].values[0]

similarity_score = list(enumerate(similarity[id_of_the_movie]))

sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse = True) 

print('Movies suggested for you : \n')

i = 1
k = 1

for movie in sorted_similar_movies:
    if(k == 1):
        k+=1
        continue
    index = movie[0]
    title_from_index = movies_data[movies_data.id==index]['movie title'].values[0]
    if (i<11):
        print(i,'.',title_from_index)
        i+=1

 Enter your favourite movie name :  Avengers


Movies suggested for you : 

1 . Avengers: Age of Ultron
2 . Captain America: Civil War
3 . Avengers: Endgame
4 . Spider-Man: Homecoming
5 . Avengers: Infinity War
6 . Captain Marvel
7 . Black Widow
8 . Skylines
9 . Come and Find Me
10 . We Can Be Heroes


In [16]:
import pickle

In [17]:
pickle.dump(similarity,open("movies_recommendation_model.sav","wb"))

In [18]:
pickle.dump(movies_data,open("movies_data.sav","wb"))